import type { ProductDetails, ProductVariant } from '../domain/Product'

const shirts = { id: 'camisetas', name: 'Camisetas', slug: 'camisetas' }
const shorts = { id: 'shorts', name: 'Shorts', slug: 'shorts' }

function createVariants(productId: string): ProductVariant[] {
  const colors = productId.includes('short') ? ['Azul', 'Cinza'] : ['Preto', 'Cinza']

  return colors.flatMap((color) =>
    ['P', 'M', 'G'].map((size) => ({
      id: `${productId}-${color.toLocaleLowerCase('pt-BR')}-${size.toLocaleLowerCase('pt-BR')}`,
      color,
      size,
      available: !(color === 'Cinza' && size === 'G'),
    })),
  )
}

const products = [
  {
    id: 'camiseta-boss',
    slug: 'camiseta-boss',
    name: 'Camiseta Boss',
    price: 89.9,
    installmentCount: 12,
    installmentValue: 8.32,
    image: '/images/bossshirt.png',
    images: ['/images/bossshirt.png'],
    category: shirts,
    featured: true,
    description: 'Camiseta masculina Boss em tecido confortável.',
  },
  {
    id: 'short-boss-azul',
    slug: 'short-boss-azul',
    name: 'Short Boss Azul',
    price: 79.9,
    installmentCount: 12,
    installmentValue: 7.39,
    image: '/images/BlueBossShorts.png',
    images: ['/images/BlueBossShorts.png'],
    category: shorts,
    featured: true,
    description: 'Short masculino Boss na cor azul.',
  },
  {
    id: 'short-boss-cinza',
    slug: 'short-boss-cinza',
    name: 'Short Boss Cinza',
    price: 79.9,
    installmentCount: 12,
    installmentValue: 7.39,
    image: '/images/GreyBossShorts.png',
    images: ['/images/GreyBossShorts.png'],
    category: shorts,
    featured: true,
    description: 'Short masculino Boss na cor cinza.',
  },
  {
    id: 'camiseta-faixa-refletiva',
    slug: 'camiseta-faixa-refletiva',
    name: 'Camiseta Faixa Refletiva',
    price: 89.9,
    installmentCount: 12,
    installmentValue: 8.32,
    image: '/images/Shirt2.png',
    images: ['/images/Shirt2.png'],
    category: shirts,
    featured: true,
    description: 'Camiseta masculina com detalhe em faixa refletiva.',
  },
  {
    id: 'camiseta-boss-essential',
    slug: 'camiseta-boss-essential',
    name: 'Camiseta Boss Essential',
    price: 84.9,
    installmentCount: 12,
    installmentValue: 7.86,
    image: '/images/bossshirt.png',
    images: ['/images/bossshirt.png'],
    category: shirts,
    featured: false,
    description: 'Camiseta masculina Boss de visual essencial.',
  },
  {
    id: 'camiseta-boss-refletiva',
    slug: 'camiseta-boss-refletiva',
    name: 'Camiseta Boss Refletiva',
    price: 94.9,
    installmentCount: 12,
    installmentValue: 8.78,
    image: '/images/Shirt2.png',
    images: ['/images/Shirt2.png'],
    category: shirts,
    featured: false,
    description: 'Camiseta masculina Boss com acabamento refletivo.',
  },
  {
    id: 'short-boss-azul-classic',
    slug: 'short-boss-azul-classic',
    name: 'Short Boss Azul Classic',
    price: 82.9,
    installmentCount: 12,
    installmentValue: 7.67,
    image: '/images/BlueBossShorts.png',
    images: ['/images/BlueBossShorts.png'],
    category: shorts,
    featured: false,
    description: 'Short masculino Boss azul em modelagem clássica.',
  },
  {
    id: 'short-boss-cinza-classic',
    slug: 'short-boss-cinza-classic',
    name: 'Short Boss Cinza Classic',
    price: 82.9,
    installmentCount: 12,
    installmentValue: 7.67,
    image: '/images/GreyBossShorts.png',
    images: ['/images/GreyBossShorts.png'],
    category: shorts,
    featured: false,
    description: 'Short masculino Boss cinza em modelagem clássica.',
  },
  {
    id: 'camiseta-boss-premium',
    slug: 'camiseta-boss-premium',
    name: 'Camiseta Boss Premium',
    price: 109.9,
    installmentCount: 12,
    installmentValue: 10.16,
    image: '/images/bossshirt.png',
    images: ['/images/bossshirt.png'],
    category: shirts,
    featured: false,
    description: 'Camiseta masculina Boss de acabamento premium.',
  },
  {
    id: 'camiseta-faixa-premium',
    slug: 'camiseta-faixa-premium',
    name: 'Camiseta Faixa Premium',
    price: 99.9,
    installmentCount: 12,
    installmentValue: 9.24,
    image: '/images/Shirt2.png',
    images: ['/images/Shirt2.png'],
    category: shirts,
    featured: false,
    description: 'Camiseta masculina com faixa em acabamento premium.',
  },
  {
    id: 'short-boss-azul-premium',
    slug: 'short-boss-azul-premium',
    name: 'Short Boss Azul Premium',
    price: 89.9,
    installmentCount: 12,
    installmentValue: 8.32,
    image: '/images/BlueBossShorts.png',
    images: ['/images/BlueBossShorts.png'],
    category: shorts,
    featured: false,
    description: 'Short masculino Boss azul de acabamento premium.',
  },
  {
    id: 'short-boss-cinza-premium',
    slug: 'short-boss-cinza-premium',
    name: 'Short Boss Cinza Premium',
    price: 89.9,
    installmentCount: 12,
    installmentValue: 8.32,
    image: '/images/GreyBossShorts.png',
    images: ['/images/GreyBossShorts.png'],
    category: shorts,
    featured: false,
    description: 'Short masculino Boss cinza de acabamento premium.',
  },
]

export const mockProducts: ProductDetails[] = products.map((product) => ({
  ...product,
  variants: createVariants(product.id),
}))
